### ISSUE TITLE
Support for TLS-Less Builds?

### ISSUE THREAD

**Issue by flosincapite** [second-state/wasmedge-quickjs#118]
Hello! My team has been using `wasmedge-quickjs` for sandboxing; it's been great! However, I notice that the recent addition of TLS support breaks our build.

Since it's an optional dependency, I thought building with `--no-default-features` would work, but I get the error

```
no `AsyncTlsConn` in `event_loop`
```

Is there any way to build _without_ TLS support?

**Comment by juntao** [comment]
Thanks!

@L-jasmine I think we should fix this. We should be able to turn off TLS via a feature flag.

**Comment by flosincapite** [comment]
Thank you for looking into this!

**Comment by L-jasmine** [comment]
@flosincapite https://github.com/second-state/wasmedge-quickjs/pull/120  
`fetch` support tls now.

**Comment by flosincapite** [comment]
I can confirm that our build chain works again, so this is no longer an issue for me. Thank you so much!

**Comment by flosincapite** [comment]
(What is your protocol for issues? Should I close this one?)

**Comment by juntao** [comment]
Hi @flosincapite 

Thank you for confirming the solution. Please go ahead and close the issue.

Cheers
Michael

**Comment by lastmjs** [comment]
I think I'm running into this issue right now. When I turn off default features I get this:

```bash
error[E0432]: unresolved import `rustls`
  --> /home/lastmjs/development/wasmedge-quickjs/src/event_loop/mod.rs:18:5
   |
18 | use rustls::OwnedTrustAnchor;
   |     ^^^^^^ use of undeclared crate or module `rustls`

error[E0432]: unresolved import `crate::event_loop::AsyncTlsConn`
   --> /home/lastmjs/development/wasmedge-quickjs/src/internal_module/wasi_net_module.rs:3:55
    |
3   | use crate::event_loop::{AsyncTcpConn, AsyncTcpServer, AsyncTlsConn};
    |                                                       ^^^^^^^^^^^^
    |                                                       |
    |                                                       no `AsyncTlsConn` in `event_loop`
    |                                                       help: a similar name exists in the module: `AsyncTcpConn`
    |
note: found an item that was configured out
   --> /home/lastmjs/development/wasmedge-quickjs/src/event_loop/mod.rs:124:12
    |
124 | pub struct AsyncTlsConn(pub(crate) tokio_rustls::client::TlsStream<tokio::net::TcpStream>);
    |            ^^^^^^^^^^^^
    = note: the item is gated behind the `tls` feature

```
