### ISSUE TITLE
how to debug this project?

### ISSUE THREAD

**Issue by oliverzy** [second-state/wasmedge-quickjs#146]
I am trying to debug wasmedge-quickjs in vscode with codelldb plugin.
Here is my lanuch config:

{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Launch Wasmedge",
      "program": "wasmedge",
      "args": ["--dir", ".:.", "target/wasm32-wasi/debug/node.wasm"],
      "cwd": "${workspaceFolder}",
      "externalConsole": true,
      "stopOnEntry": true
    }
  ]
}
and I place a breakpoint in the entrypoint "src/main.rs", but it cannot break.

**Comment by L-jasmine** [comment]
Currently, WasmEdge does not support debugging WebAssembly. To my knowledge, only V8 can debug WebAssembly, but V8’s WASI implementation differs slightly from the one used in this project. What bug are you trying to fix?

**Comment by oliverzy** [comment]
OK, I am wondering whether we can use rquickjs binding for quickjs integration, that project is maintained more actively.
So I am trying to understand the current implementation.

**Comment by L-jasmine** [comment]
Do you want to use it in your own non-WASM projects?

**Comment by oliverzy** [comment]
My project is also based on wasm but it will be run on the browser to simulate a node.js enviroment.
I don't know whether this is the target of wasmedge-quickjs.

**Comment by L-jasmine** [comment]
> My project is also based on wasm but it will be run on the browser to simulate a node.js enviroment. I don't know whether this is the target of wasmedge-quickjs.

I apologize, but the goal of our project is to run in the WASI environment. However, there are many other projects that run QuickJS in the browser, as well as browser-based Node.js environments. You can refer to them.

**Comment by oliverzy** [comment]
Thanks, this is a great project, I like it. Rust and WebAssembly are both quite new for me, wasmedge-quickjs gives me a whole picture how to use these technology to run javascript everywhere.

Once I have made some progress, I'll let you know.
