### ISSUE TITLE
How to convert JsValue to Rust type?

### ISSUE THREAD

**Issue by zhenjunMa** [second-state/wasmedge-quickjs#25]
JS code is as follows:
```
export async function wait_simple_val (key){
    return "abc"
}
```

`wasmedge-quickjs/examples/embed_js/src/main.rs`

https://github.com/second-state/wasmedge-quickjs/blob/0da2e47c27b6c26192d0f20c5c5e67666147cdd0/examples/embed_js/src/main.rs#L177-L178

the `result` is JsValue, and i got `promise result:String(JsString(abc))`

my question is how can i get the real result "abc" from the JsValue? any doc about this?

**Comment by L-jasmine** [comment]
```
if let JsValue::String(js_string) = result {
   let s:String = js_string.to_string();
   // todo something
}
```

**Comment by L-jasmine** [comment]
> JS code is as follows:
> 
> ```
> export async function wait_simple_val (key){
>     return "abc"
> }
> ```
> 
> `wasmedge-quickjs/examples/embed_js/src/main.rs`
> 
> https://github.com/second-state/wasmedge-quickjs/blob/0da2e47c27b6c26192d0f20c5c5e67666147cdd0/examples/embed_js/src/main.rs#L177-L178
> 
> the `result` is JsValue, and i got `promise result:String(JsString(abc))`
> 
> my question is how can i get the real result "abc" from the JsValue? any doc about this?

```
if let JsValue::String(js_string) = result {
   let s:String = js_string.to_string();
   // todo something
}
```
