### ISSUE TITLE
Add the support of `fs` and `env`

### ISSUE THREAD

**Issue by DarumaDocker** [second-state/wasmedge-quickjs#43]
https://github.com/second-state/wasmedge-quickjs/blob/main/example_js/react18_ssr/main.mjs#L8
Currently, the CSS can only be imported as a module in the example.

But in reality, the assets will be built with some random file names, something like `main.073c9b0a.css`.
This requires the server can read the content from the file system.

As Wasi has supplied the files and env API, it would be great to add modules like 'wasi_fs' and 'wasi_env`.

**Comment by L-jasmine** [comment]
About `fs`. In quickjs 'std' module has [some function](https://github.com/quickjs-zh/QuickJS/blob/a6ba08b733aa0d3721a65bfff4ad293b3b52fb66/tests/test_std.js).
If you need other fs function, please tell me more.

About `env`. I don't know what function is needed. Can you show me how you want to use it?

**Comment by DarumaDocker** [comment]
In Nodejs, I can get environment variables via `process.env`. The typical scenario is to set its port when the server starts.

**Comment by L-jasmine** [comment]
https://github.com/second-state/wasmedge-quickjs/pull/44

**Comment by sergeevabc** [comment]
Is there a way to make QuickJS work with the following code instead of NodeJS?

``` console
$ cat file.txt | node -p "fs.readFileSync(0).toString().trim().split(/\s+/)[2]"
```

Right now it says `ReferenceError: 'fs' is not defined`. I try to define `fs` via `const fs = require('fs')`, but then it says `ReferenceError: 'require' is not defined`.
