### ISSUE TITLE
Hydrate is not a function

### ISSUE THREAD

**Issue by tpmccallum** [second-state/wasmedge-quickjs#52]
Hi
I have a few observations whilst building a new React SSR application.

I get an error (in the client's browser console) as shown below, when the app is started. **Interestingly, the page still loads successfully**. But I am not wanting to just ignore this browser console error (in case we need to address this)

```
Uncaught TypeError: n.createRoot(...).hydrate is not a function
```
Here is my understanding of render vs hydrate

Render provides a way for the app to render a React element into the DOM and return a reference to the component.

Hydrate is essentially the same as render. However, hydrate is used to hydrate a container whose HTML contents were rendered by React's ReactDOMServer.

The original code in the `src/index.js` file (which the `create-react-app` command generated) is as follows

```Javascript
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
Interestingly the above original code works even when we have already implemented all of the other SSR conversions (`server/index.js` and `rollup.config.js` etc.) and are starting the server using `wasmedge` command (as apposed to npm). 

Please note, that there is no error in the browser console with the above code (`root.render`).

We of course change the `root.render` to `root.hydrate` in our documentation so I went ahead and did that. The `root.hydrate` generates the above error. I then also tried importing and using `ReactDOMServer` instead of just `ReactDOM` but the error still persists.

Do you have any ideas about solving this error.
Thanks so much
Tim

**Comment by juntao** [comment]
Do you have this error when you do regular React SSR without wasmedge?

**Comment by tpmccallum** [comment]
Yes, interestingly if I run the exact same source code via `npm start` which is served on `localhost:3000` the same "`root.hydrate` is not a function" error appears in the browser's console.

![image](https://user-images.githubusercontent.com/9831342/168460444-15e8d275-0cdc-4932-9a38-a08e21a4eace.png)

Also the same error exists when I use `ReactDOMServer` instead of just `ReactDOM` i.e.

```
import ReactDOMServer from 'react-dom/client';
const root = ReactDOMServer.createRoot(document.getElementById('root'));
root.hydrate(
// snip ...
```

**Comment by tpmccallum** [comment]
Thankfully for now `root.render` works just fine for regular SSR 

![image](https://user-images.githubusercontent.com/9831342/168460637-5f32645c-5107-4ebe-a736-349b142bbdf2.png)

As well as with WasmEdge SSR.

![image](https://user-images.githubusercontent.com/9831342/168460693-a0524902-c30f-4b0a-8553-8c73ee5f8e44.png)

**Comment by juntao** [comment]
Since this occurs with regular SSR, perhaps you could ask in stackoverflow or official React forums?


> Yes, interestingly if I run the exact same source code via `npm start` which is served on `localhost:3000` the same "`root.hydrate` is not a function" error appears in the browser's console.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/9831342/168460444-15e8d275-0cdc-4932-9a38-a08e21a4eace.png)
> 
> 
> 
> Also the same error exists when I use `ReactDOMServer` instead of just `ReactDOM` i.e.
> 
> 
> 
> ```
> 
> import ReactDOMServer from 'react-dom/client';
> 
> const root = ReactDOMServer.createRoot(document.getElementById('root'));
> 
> root.hydrate(
> 
> // snip ...
> 
> ```

**Comment by tpmccallum** [comment]
Link to question for our convenience

- https://stackoverflow.com/questions/72253995/why-do-reactdomserver-and-reactdom-give-the-root-hydrate-is-not-a-function-err

**Comment by tpmccallum** [comment]
Please find a solution to this issue; as per a response via the above stackoverflow link.

In summary `hydrate` has been replaced with `hydrateRoot` in React 18.

```
hydrateRoot(container, element[, options])
```
The code for this SSR example was altered as per the following code block.

```
// Before
import ReactDOM from 'react-dom/client';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.hydrate(
  <React.StrictMode>
   <App />
 </React.StrictMode>
);

// After
import { hydrateRoot } from 'react-dom/client';
const container = document.getElementById('root');
const root = hydrateRoot(container, <App />);
```

After implementing this slightly different syntax the error was resolved.

There is also official documentation for [hydrateRoot](https://reactjs.org/docs/react-dom-client.html#hydrateroot)
