### ISSUE TITLE
Question on Javascript example

### ISSUE THREAD

**Issue by Shawn-Fan** [second-state/wasmedge-quickjs#55]
Following the the instruction to run the example code in windows 10 environment but an error message. 
_wasmedge --dir .:. ../target/wasm32-wasi/release/wasmedge_quickjs.wasm hello.js WasmEdge Runtime
error message:
[error] Bind guest directory failed:52

Could you let me know the problem? thanks

**Comment by L-jasmine** [comment]
@hydai pls look this

**Comment by hydai** [comment]
Hi @Shawn-Fan and @L-jasmine,
Currently, most of the WASI functions are not yet supported on the Windows platform.
I am not sure what's the content of `hello.js`. If the script doesn't contain anything related to the filesystem, then please try to remove `--dir .:.` in the command line.

We are working on this: https://github.com/WasmEdge/WasmEdge/issues/1477

**Comment by L-jasmine** [comment]
@hydai  ../target/wasm32-wasi/release/wasmedge_quickjs.wasm need `hello.js`.
@Shawn-Fan so you need use linux to try it.

**Comment by hydai** [comment]
Ah-ha... So the filesystem is needed. Then, please try linux instead. Sorry about that :-(

**Comment by Shawn-Fan** [comment]
Thanks for your response.

**Comment by liudonghua123** [comment]
I have a similar problem when running python.wasm on windows from https://wasmlabs.dev/articles/python-wasm32-wasi/.

```
D:\Downloads>wasmedge --dir /:D:/Downloads/ python-3.11.3-wasmedge.wasm
[2023-06-05 10:27:27.048] [error] Bind guest directory failed:44
^C
D:\Downloads>wasmedge --dir /:D:\Downloads\ python-3.11.3-wasmedge.wasm
[2023-06-05 10:27:37.568] [error] Bind guest directory failed:44
^C
D:\Downloads>
```

I tried wasmtime, it's ok.

```
D:\Downloads>wasmtime run --mapdir /::D:/Downloads python-3.11.3.wasm
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr 28 2023, 09:49:53) [Clang 15.0.7 ] on wasi
Type "help", "copyright", "credits" or "license" for more information.
>>> 1+2
3
>>> exit()
```

**Comment by alabulei1** [comment]
@L-jasmine @hydai Please take a look. Thanks!
