### ISSUE TITLE
Dome Hello World in readme may not work

### ISSUE THREAD

**Issue by Puellaquae** [second-state/wasmedge-quickjs#62]
If run
```bash
$ cd example_js
$ wasmedge --dir .:. ../target/wasm32-wasi/release/wasmedge_quickjs.wasm hello.js WasmEdge Runtime
```
which written in [readme](https://github.com/second-state/wasmedge-quickjs#run) will show ``ReferenceError: could not load module filename 'process'``. The module files are not loaded into wasm environment (or maybe there has other way to access the module files that I don't know).

Or use this?
```bash
$ wasmedge --dir .:. ./target/wasm32-wasi/release/wasmedge_quickjs.wasm example_js/hello.js WasmEdge Runtime
```

**Comment by L-jasmine** [comment]
```shell
$ wasmedge --dir .:. ./target/wasm32-wasi/release/wasmedge_quickjs.wasm example_js/hello.js WasmEdge Runtime
```
because wasmedge_quickjs.wasm will load 'process' from './modules'.

I will update README.md to fix it.

**Comment by Puellaquae** [comment]
Hi @L-jasmine , can let me to fix this?

**Comment by alabulei1** [comment]
> Hi @L-jasmine , can let me to fix this?

@Puellaquae  Much appreciated. Please do it!

**Comment by vishalchandra** [comment]
This does not seem to be working from this example.

```
setTimeout(() => {
    print('timeout 2s');
}, 2000);
```
