### ISSUE TITLE
Unable to start server - OS error 28 on Ubuntu 20.04

### ISSUE THREAD

**Issue by jcuffe** [second-state/wasmedge-quickjs#83]
Originates from this line: https://github.com/second-state/wasmedge-quickjs/blob/main/modules/http.js#L764

Machine details:
```
❯ uname -sr
Linux 5.15.0-46-generic

❯ uname -a
Linux bropletop 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

❯ wasmedge --version
wasmedge version 0.9.1

❯ cargo --version
cargo 1.62.0 (a748cf5a3 2022-06-08)
```

Using a pre-built image of the much simpler HTTP app works for me via cri-o and crun, but I'm not aware of such an image for the react examples, and I am unable to run the the simple HTTP example bytecode locally either (same error).

**Comment by juntao** [comment]
Can you upgrade to wasmedge 0.11? Just re-run the WasmEdge installer command on your system and it will upgrade for you. Thank you!

**Comment by jcuffe** [comment]
Worked, thanks!
